### ISSUE TITLE
all counties, one year

### ISSUE THREAD

**Issue by WJohnC** [4gh/WorldBankData.jl#12]
There does not seem to be a convenient way to download data for all countries. In this regard, note that WDI lumps countries together with regions, so there should be some way to download one set without the other.

An error is generated if I try to download data for one year by specifying the same start and end year.

**Comment by 4gh** [comment]
Sorry for the long delay. I released a new version. You should be able to set startyear and endyear to the same value. To get all countries you can use "all" as the country code.
