### ISSUE TITLE
libcurl

### ISSUE THREAD

**Issue by juanklopper** [4gh/WorldBankData.jl#6]
This package worked like a charm a few weeks ago.  Tried to use it today and received this error:
LoadError: error compiling get: error compiling setup_easy_handle: could not load library "libcurl"
libcurl: cannot open shared object file: No such file or directory
while loading In[3], in expression starting on line 1

 in get at /home/juan/.julia/v0.4/HTTPClient/src/HTTPC.jl:534
 in download_parse_json at /home/juan/.julia/v0.4/WorldBankData/src/WorldBankData.jl:16

Please help!

**Comment by 4gh** [comment]
Thank you for reporting this. This looks like an install issue with libcurl on your machine. You might want to try reinstalling libcurl on your operating system. Unfortunately I don't think there is much I can do to help.

**Comment by juanklopper** [comment]
Thanks.  Just FYI, it only happened on my MAC.  Linux and Windows machines had no issues.  This morning, after doing a Pkg.update() in Julia, everything is working well!

We are hoping to showcase _WorkBankData_ in an upcoming Coursera course on Julia.
