### ISSUE TITLE
UndefVarError

### ISSUE THREAD

**Issue by juanklopper** [4gh/WorldBankData.jl#7]
The  code:

**total_population_2015 = wdi("SP.POP.TOTL", ["BR", "RU", "IN", "CN", "ZA", "US"], 2015)**

to search for the population sizes of the listed countries in 2015 returns this error:

UndefVarError: displaysize not defined

 in writemime at /Users/juanklopper/.julia/v0.4/DataFrames/src/abstractdataframe/io.jl:181
 in sprint at iostream.jl:206
 in display_dict at /Users/juanklopper/.julia/v0.4/IJulia/src/execute_request.jl:38
 in execute_request at /Users/juanklopper/.julia/v0.4/IJulia/src/execute_request.jl:195
 in eventloop at /Users/juanklopper/.julia/v0.4/IJulia/src/IJulia.jl:138
 in anonymous at task.jl:447

Any suggestions?

**Comment by juanklopper** [comment]
PS.  Forgot to mention, running Julia 0.4.6 and in the same notebook also using DataFrames, Plots, and HypothesisTests.  Also did fresh Pkg.update().

**Comment by 4gh** [comment]
The backtrace indicates you might be running this in IJulia. If so, could you please try it directly in the julia shell? It works for me with the exact same julia version when I run julia directly from the command line.

**Comment by juanklopper** [comment]
After update to IJulia, the problem is resolved.  Thanks.

**Comment by 4gh** [comment]
OK. Thanks for letting me know.
